set -g mouse on
set -g default-terminal "tmux-256color"

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set -g renumber-windows on

# Custom prefix keymap
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Custom yanking and clipboard configuration
set -g set-clipboard on
set-window-option -g mode-keys vi
bind -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"
unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode when dragging with mouse

# Custom clear-history keymap
bind-key b send-keys -R C-l \; clear-history

# Custom split-window keymaps
unbind %
unbind '"'
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Custom resize-pane keymaps
unbind C-Up
unbind C-Down
unbind C-Left
unbind C-Right
unbind M-Up
unbind M-Down
unbind M-Left
unbind M-Right
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# New window switching keymaps
bind -n M-h previous-window
bind -n M-l next-window

# New kill all other panes keymap
bind o kill-pane -a

# New kill all other windows keymap
bind O kill-window -a

# Catppuccin plugin configuration
set -g @catppuccin_flavor "macchiato" # latte, frappe, macchiato or mocha
set -g @catppuccin_window_status_style "basic" # basic, rounded, slanted, custom, none
set -g @catppuccin_status_background "none"

# Run catppuccin plugin
run '~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux'

# Make the status line pretty and add some modules
set -g status-position top
set -g status 2
set -g status-format[1] ""
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"

# Run various plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

run '~/.tmux/plugins/tpm/tpm'
