import = ["~/.config/alacritty/themes/themes/catppuccin_latte.toml"]

[font]
normal = { family = "MesloLGS NF", style = "Regular" }
size = 14.00

[keyboard]
bindings = [
  { key = "F", mods = "Command | Control", action = "ToggleSimpleFullscreen" },
]

[window]
opacity = 1
padding = { y = 36 }

[env]
TERM = "xterm-256color"