# import = ["~/.config/alacritty/themes/themes/palenight.toml"]
# import = ["~/.config/alacritty/themes/themes/cyber_punk_neon.toml"]
import = ["~/.config/alacritty/themes/themes/hyper.toml"]

[font]
normal = { family = "MesloLGS NF", style = "Regular" }
size = 14.00

[keyboard]
bindings = [
  { key = "F", mods = "Command | Control", action = "ToggleSimpleFullscreen" },
]

[window]
opacity = 1
padding = { y = 36 }
